### ISSUE TITLE
Missing Git History?

### ISSUE THREAD

**Issue by enzolutions** [backdrop-contrib/simplify#1]
Hola @BWPanda 

Looks like you loose the git history. Can you delete this repor and follow this instructions

```
git clone --branch 7.x-3.x http://git.drupal.org/project/simplify.git
git checkout -b 1.x-1.x

// Replace the current status of your migration of email 

git remote remove origin
git remote add origin git@github.com:backdrop-contrib/email.git
git push origin
```

Thanks in advance, ignore and close if I'm wrong

**Comment by ghost** [comment]
I think you're wrong. Here's the git commit history for Simplify showing Mark Shust's initial commit back in 2010 (before I took over as maintainer): https://github.com/backdrop-contrib/simplify/commits/1.x-1.x?page=2

Closing, but feel free to re-open if I misunderstood.
