### ISSUE TITLE
TypeError with imported content type

### ISSUE THREAD

**Issue by conniboe** [backdrop-contrib/simplify#19]
Hi everybody

When importing a content type and then trying to configure at

admin/structure/types/manage/new-content-type

I get

TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in array_filter() (Zeile 85 von .../modules/simplify/simplify.module).

The same if I create a content type and want to configure it later.

This is because the variable ``

$type_is_new = property_exists($type, 'is_new');

in  function function simplify_form_node_type_form_alter(&$form, &$form_state, $form_id)
is only TRUE after the first time saved. This is never true for imported content types.

Would'nt it be better to check the dimension of the array

$zwi = config_get('simplify.nodes', $type->type);
// an array containing data of all content types or only the specified content type

$dim = (gettype(reset($zwi)) == "array");
// dim = TRUE if 2-dimensional ist -> a new content type 
// dim = FALSE if1-dimensional 

    '#default_value' => !$dim ? array_filter(config_get('simplify.nodes', $type->type)) : array(),   

Regards
Conni

**Comment by yorkshire-pudding** [comment]
Hi @conniboe . Thanks for your report.  I have previously tackled some cases where Simplify was not working for new content types in #12 and #17 .  Please can you give more information about how your content type is being imported so I can reproduce and address this.

**Comment by conniboe** [comment]
Hi
I exported / imported a content type from one backdrop site to another via configuration management.
and in another try
I added a new content type and saved it. I wanted to add fields later. 

In both cases the TypeError described above appeared. The reason, I guess: there exists no configuration for the new type yet but the module tries to load it via config_get(), because  $type_is_new is FALSE and so the functions returns NULL.

function simplify_form_node_type_form_alter(&$form, &$form_state, $form_id) {
...
array_filter(config_get('simplify.nodes', $type->type))
in line 85 

function simplify_form_node_form_alter(&$form, &$form_state, $form_id) {
...
array_filter(config_get('simplify.global', 'nodes'))
in line 251

I tried a solution without $type_is_new and figured out that the dimension of the returned array could possibly be the way to go.

Regards
Conni

**Comment by yorkshire-pudding** [comment]
Hi @conniboe 

> I added a new content type and saved it. I wanted to add fields later.

I can't reproduce an error in this scenario.  I created a content type and clicked on "Save Content Type" rather than "Save and Add Fields" and there was no error.  There was also no error going back into the content type.

> I exported / imported a content type from one backdrop site to another via configuration management.

I'm still not clear on how to reproduce this.  In general, exporting a content type from one site to another via config can be tricky because there are several config files involved.  Please document the exact steps you took so I can reproduce this.

Incidentally, I do this regularly when I am deploying config changes from my local site to my hosted site, but that is whole site config and includes the simplify config too as the source site is very similar in setup to the target site.

**Comment by yorkshire-pudding** [comment]
@conniboe - are you able to provide more detailed steps to reproduce?

**Comment by conniboe** [comment]
Hello Martin

I have a backdrop page with simplify module already installed and configured. 
files/config.../active/simplify.nodes.json contains all existing content types 


/admin/config/development/configuration/single

importing a content type from another backdrop page

admin/structure/types shows the newly imported content type

click on *configure*

Standort	http://localhost/bd-one/admin/structure/types/manage/image
Referrer	http://localhost/bd-one/admin/structure/types
Benachrichtigung	TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in array_filter() (Zeile 85 von /var/www/html/bd-one/modules/simplify/simplify.module).

simplify.nodes.json has not changed, the newly imported content type is not shown here.

If I try to add content -> node/add/image

Standort	http://localhost/bd-one/node/add/image
Referrer	http://localhost/bd-one/admin/structure/types
Benachrichtigung	TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in array_filter() (Zeile 252 von /var/www/html/bd-one/modules/simplify/simplify.module).



In contrast: when I add  a new content type via admin/structure/types/add, the new content type is immediately added to simplify.nodes.json

if I delete the content-type it ist not deleted in simplify.nodes.json

I think, because simplify.nodes.json is not updated, a configuration cannot be found and

config_get('simplify.nodes', $type->type)

returns NULL.

regards Conni

**Comment by yorkshire-pudding** [comment]
Hi @conniboe 
Thank you for your more detailed explanation. I think I have what I need now to take this forward.
