### ISSUE TITLE
Node type edit form is broken

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop-contrib/simplify#2]
![vtabs-broken](https://cloud.githubusercontent.com/assets/16973264/25027289/81a57b06-20bc-11e7-97de-c66100481088.jpg)

Some fieldsets are separated from vertical tabs.

**Comment by Al-Rozhkov** [comment]
Sorry. Looks like it is not related to Simplify. I will try to find true reason and reopen if needed.

**Comment by klonos** [comment]
For the record: https://github.com/backdrop/backdrop-issues/issues/2641 ...fixed!
