### ISSUE TITLE
Hide "Show row weights"

### ISSUE THREAD

**Issue by kswan** [backdrop-contrib/simplify#5]
Add an option to hide the "Show row weights" link on fields with multiple values.

**Comment by ghost** [comment]
Thanks for the suggestion @kswan. Unfortunately I'm not sure it's going to be possible, since that link is added via javascript in `tabledrag.js`... I can't see a way to add it into the existing functionality for Simplify.

**Comment by kswan** [comment]
I understand. Thank you for checking. I'll investigate hiding it with CSS.
